-- Project 04: replace non-partitioned orders / order_item with RANGE partitions by order_date
-- Run AFTER bulk load OR use 11_migrate_to_partitioned.sql to move data from existing tables.
-- WARNING: drops orders + order_item (CASCADE removes dependent FKs only on these tables).

BEGIN;

DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
    order_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_date     TIMESTAMP      NOT NULL,
    seller_id      INT            NOT NULL REFERENCES seller (seller_id),
    status         VARCHAR(20)    NOT NULL,
    total_amount   NUMERIC(12, 2) NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    PRIMARY KEY (order_id, order_date)
) PARTITION BY RANGE (order_date);

CREATE TABLE orders_2025_08 PARTITION OF orders
    FOR VALUES FROM ('2025-08-01 00:00:00') TO ('2025-09-01 00:00:00');

CREATE TABLE orders_2025_09 PARTITION OF orders
    FOR VALUES FROM ('2025-09-01 00:00:00') TO ('2025-10-01 00:00:00');

CREATE TABLE orders_2025_10 PARTITION OF orders
    FOR VALUES FROM ('2025-10-01 00:00:00') TO ('2025-11-01 00:00:00');

CREATE TABLE order_item (
    order_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id       BIGINT         NOT NULL,
    order_date     TIMESTAMP      NOT NULL,
    product_id     INT            NOT NULL REFERENCES product (product_id),
    quantity       INT            NOT NULL,
    unit_price     NUMERIC(10, 2) NOT NULL,
    subtotal       NUMERIC(12, 2) NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    PRIMARY KEY (order_item_id, order_date),
    FOREIGN KEY (order_id, order_date) REFERENCES orders (order_id, order_date)
) PARTITION BY RANGE (order_date);

CREATE TABLE order_item_2025_08 PARTITION OF order_item
    FOR VALUES FROM ('2025-08-01 00:00:00') TO ('2025-09-01 00:00:00');

CREATE TABLE order_item_2025_09 PARTITION OF order_item
    FOR VALUES FROM ('2025-09-01 00:00:00') TO ('2025-10-01 00:00:00');

CREATE TABLE order_item_2025_10 PARTITION OF order_item
    FOR VALUES FROM ('2025-10-01 00:00:00') TO ('2025-11-01 00:00:00');

-- Index requested for product_id lookups (create on parent; attaches to all partitions)
CREATE INDEX order_item_product_id_idx ON order_item (product_id);

COMMIT;
