-- Migrate non-partitioned orders + order_item -> partitioned tables (monthly, Aug–Oct 2025).
-- Prerequisites:
--   1) sql/00_prep_alter_tables.sql applied; order_item.order_date / created_at populated.
--   2) No concurrent writers.

BEGIN;

ALTER TABLE IF EXISTS orders RENAME TO orders_old;
ALTER TABLE IF EXISTS order_item RENAME TO order_item_old;

CREATE TABLE orders (
    order_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_date     TIMESTAMP      NOT NULL,
    seller_id      INT            NOT NULL REFERENCES seller (seller_id),
    status         VARCHAR(20)    NOT NULL,
    total_amount   NUMERIC(12, 2) NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    PRIMARY KEY (order_id, order_date)
) PARTITION BY RANGE (order_date);

CREATE TABLE orders_2025_08 PARTITION OF orders
    FOR VALUES FROM ('2025-08-01 00:00:00') TO ('2025-09-01 00:00:00');
CREATE TABLE orders_2025_09 PARTITION OF orders
    FOR VALUES FROM ('2025-09-01 00:00:00') TO ('2025-10-01 00:00:00');
CREATE TABLE orders_2025_10 PARTITION OF orders
    FOR VALUES FROM ('2025-10-01 00:00:00') TO ('2025-11-01 00:00:00');

INSERT INTO orders (order_id, order_date, seller_id, status, total_amount, created_at)
SELECT order_id, order_date, seller_id, status, total_amount, created_at
FROM orders_old;

SELECT setval(
    pg_get_serial_sequence('public.orders', 'order_id'),
    (SELECT COALESCE(MAX(order_id), 1) FROM orders)
);

CREATE TABLE order_item (
    order_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id       BIGINT         NOT NULL,
    order_date     TIMESTAMP      NOT NULL,
    product_id     INT            NOT NULL REFERENCES product (product_id),
    quantity       INT            NOT NULL,
    unit_price     NUMERIC(10, 2) NOT NULL,
    subtotal       NUMERIC(12, 2) NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    PRIMARY KEY (order_item_id, order_date),
    FOREIGN KEY (order_id, order_date) REFERENCES orders (order_id, order_date)
) PARTITION BY RANGE (order_date);

CREATE TABLE order_item_2025_08 PARTITION OF order_item
    FOR VALUES FROM ('2025-08-01 00:00:00') TO ('2025-09-01 00:00:00');
CREATE TABLE order_item_2025_09 PARTITION OF order_item
    FOR VALUES FROM ('2025-09-01 00:00:00') TO ('2025-10-01 00:00:00');
CREATE TABLE order_item_2025_10 PARTITION OF order_item
    FOR VALUES FROM ('2025-10-01 00:00:00') TO ('2025-11-01 00:00:00');

INSERT INTO order_item (
    order_item_id, order_id, order_date, product_id, quantity, unit_price, subtotal, created_at
)
SELECT
    order_item_id,
    order_id::BIGINT,
    order_date,
    product_id,
    quantity,
    unit_price::NUMERIC(10, 2),
    subtotal,
    created_at
FROM order_item_old;

SELECT setval(
    pg_get_serial_sequence('public.order_item', 'order_item_id'),
    (SELECT COALESCE(MAX(order_item_id), 1) FROM order_item)
);

CREATE INDEX order_item_product_id_idx ON order_item (product_id);

DROP TABLE order_item_old;
DROP TABLE orders_old;

COMMIT;
